## Lectura preliminar

Considere las siguientes propuestas de implementacion para obtener $A^{2}$, es decir, elevar una matriz al cuadrado:
* np.power(A,2)
* np.dot(A,A)
* A @ A
* np.linalg.matrix_power(A,2)

¿Son todas estas alternativas equivalentes? Si no lo fueran, explique.

In [ ]:
import numpy as np

### numpy.power 

* Calcula la potencia elemento a elemento
* No eleva la matriz al cuadrado en el sentido matricial
* Eleva cada elemento al cuadrado

[numpy.power — NumPy v1.25 Manual](https://numpy.org/doc/stable/reference/generated/numpy.power.html)

First array elements raised to powers from second array, element-wise.

Raise each base in x1 to the positionally-corresponding power in x2. x1 and x2 must be broadcastable to the same shape.

An integer type raised to a negative integer power will raise a ValueError.

Negative values raised to a non-integral value will return nan. To get complex results, cast the input to complex, or specify the dtype to be complex (see the example below).

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x1,x2)

array([ 0.,  1.,  8., 27., 16.,  5.])

The ** operator can be used as a shorthand for np.power on ndarrays.

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

In [ ]:
# Calcula la potencia elemento a elemento
# No eleva la matriz al cuadrado en el sentido matricial
# Eleva cada elemento al cuadrado

A = np.array([ [2, 2], [2, 2] ])
np.power(A,2)

array([[4, 4],
       [4, 4]])

### numpy.dot

* Calcula el producto punto (producto matricial) de A consigo misma
* El resultado es la multiplicación de matrices estándar, y es equivalente a $A^2$ en términos matriciales. Esta es la forma correcta de elevar una matriz al cuadrado.

[numpy.dot — NumPy v1.25 Manual](https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot)


Dot product of two arrays. Specifically,

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

* If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

* If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

* If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

* If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

```dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])```




In [ ]:
A = np.array([ [2, 2], [2, 2] ])
np.dot(A,A)

array([[8, 8],
       [8, 8]])

### numpy.linalg

[Linear algebra (numpy.linalg) — NumPy v1.25 Manual](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg)

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient low level implementations of standard linear algebra algorithms. Those libraries may be provided by NumPy itself using C versions of a subset of their reference implementations but, when possible, highly optimized libraries that take advantage of specialized processor functionality are preferred. Examples of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries are multithreaded and processor dependent, environmental variables and external packages such as threadpoolctl may be needed to control the number of threads or specify the processor architecture.


**The ```@``` operator**

Introduced in NumPy 1.10.0, the ```@``` operator is preferable to other methods when computing the matrix product between 2d arrays. The numpy.matmul function implements the ```@``` operator.


In [ ]:
# np.dot(A, A) es equivalente a:
A @ A

array([[8, 8],
       [8, 8]])

### np.linalg.matrix_power

* Esta función calcula la potencia de una matriz en términos de la multiplicación de matrices. También es equivalente a A^2 en términos matriciales.
* Usa un algoritmo eficiente

[numpy.linalg.matrix_power — NumPy v1.25 Manual](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html#numpy.linalg.matrix_power)

Raise a square matrix to the (integer) power n.

For positive integers n, the power is computed by repeated matrix squarings and matrix multiplications. If n == 0, the identity matrix of the same shape as M is returned. If n < 0, the inverse is computed and then raised to the abs(n).